name: Firestore Export Base64

on:
  workflow_dispatch: # Déclenchement manuel depuis l'onglet Actions

jobs:
  export_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install firebase-admin beautifulsoup4

      - name: Run Export and Clean
        env:
          # C'est ici que la magie opère
          FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
        run: python scripts/export_and_clean.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: annotation-ready-csv
          path: data_to_annotate_*.csv